PierresTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace PierresTreats.Models
{
    public class Treat
    {
        public int TreatId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public List<FlavorTreat> JoinEntities { get; }
        public ApplicationUser User { get; set; }
    }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
    [Authorize]
    public class FlavorsController : Controller
    {
        private readonly PierresTreatsContext _db;

        public FlavorsController(PierresTreatsContext db)
        {
            _db = db;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(_db.Flavors.ToList());
        }
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Flavor thisFlavor = _db.Flavors
                                        .Include(flavor => flavor.JoinEntities)
                                        .ThenInclude(join => join.Treat)
                                        .FirstOrDefault(flavor => flavor.FlavorId == id);
            return View(thisFlavor);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Flavor flavor)
        {
            if (!ModelState.IsValid)
            {
                return View(flavor);
            }
            else
            {
                _db.Flavors.Add(flavor);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult AddTreat(int id)
        {
            Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
            ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Description");
            return View(thisFlavor);
        }
        [HttpPost]
        public ActionResult AddTreat(Flavor flavor, int treatId)
        {
#nullable enable
            FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
#nullable disable
            if (joinEntity == null && treatId != 0)//check here? is not or is?
            {
                _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = flavor.FlavorId });
        }

        public ActionResult Edit(int id)
        {
            Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
            return View(thisFlavor);
        }

        [HttpPost]
        public ActionResult Edit(Flavor flavor)
        {
            _db.Flavors.Update(flavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
            return View(thisFlavor);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
            _db.Flavors.Remove(thisFlavor);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DeleteJoin(int joinId)
        {
            FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
            _db.FlavorTreats.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
    [Authorize]
    public class TreatsController : Controller
    {
        private readonly PierresTreatsContext _db;

        public TreatsController(PierresTreatsContext db)
        {
            _db = db;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(_db.Treats.ToList());
        }
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Treat thisTreat = _db.Treats
                                        .Include(treat => treat.JoinEntities)
                                        .ThenInclude(join => join.Flavor)
                                        .FirstOrDefault(treat => treat.TreatId == id);
            return View(thisTreat);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Treat treat)
        {
            if (!ModelState.IsValid)
            {
                return View(treat);
            }
            else
            {
                _db.Treats.Add(treat);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult AddFlavor(int id)
        {
            Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
            ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
            return View(thisTreat);
        }
        [HttpPost]
        public ActionResult AddFlavor(Treat treat, int flavorId)
        {
#nullable enable
            FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
            if (joinEntity == null && flavorId != 0)//check here? is not or is?
            {
                _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = treat.TreatId });
        }

        public ActionResult Edit(int id)
        {
            Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
            return View(thisTreat);
        }

        [HttpPost]
        public ActionResult Edit(Treat treat)
        {
            _db.Treats.Update(treat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
            return View(thisTreat);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
            _db.Treats.Remove(thisTreat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DeleteJoin(int joinId)
        {
            FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
            _db.FlavorTreats.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@{
    Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Assign a flavor to @Html.DisplayFor(model => model.Name)</h2>

<br>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select Flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Add a Flavor", "Create", "Flavors")</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

PierresTreats/Views/Treats/Create.cshtml
@{
    Layout = "_Layout";
}

@model PierresTreats.Models.Treat



<h4>Add a new treat</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger"})</p>

@using (Html.BeginForm())
{
    @Html.LabelFor(m => m.Name)
    @Html.TextBoxFor(m => m.Name)
    @Html.LabelFor(m => m.Description)
    @Html.TextBoxFor(m => m.Description)

    <input type="submit" value="Add new treat" />
}
<p>@Html.ActionLink("Show all treats", "Index")</p>

PierresTreats/Views/Treats/Delete.cshtml
@{
    Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(m => m.Name): @Html.DisplayFor(m => m.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

PierresTreats/Views/Treats/Details.cshtml
@{
    Layout = "_Layout";
}

@model PierresTreats.Models.Treat;
@using PierresTreats.Models;
@using System.Collections.Generic;

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(m => m.Name) : @Html.DisplayFor(m => m.Name)</h3>
<h3>@Html.DisplayNameFor(m => m.Description) : @Html.DisplayFor(m => m.Description)</h3>
<h3>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId})</h3>
<h3>@Html.ActionLink("Create a new treat", "Create")</h3>
<hr>
@if (@Model.JoinEntities.Count == 0)
{
    <p>This Treat has no associated flavor.</p>
}
else
{
    <h4>This treat has the following flavors associated:</h4>
    <ul>

    @foreach (FlavorTreat join in Model.JoinEntities)
        {
            <li>Flavor:
                <br>
                @join.Flavor.Description
            </li>
            @using (Html.BeginForm("DeleteJoin", "Treats"))
            {
                @Html.Hidden("joinId", @join.FlavorTreatId)
                <input type="submit" value="Delete" />
            }
        }
    </ul>
}
</ul>

<br>
@Html.ActionLink("Tag a flavor", "AddFlavor", new { id = Model.TreatId }) to @Html.DisplayFor(m =>
m.Name)
<br>
@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId})

PierresTreats/Views/Treats/Edit.cshtml
@{
    Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Edit</h2>

<h4>Edit this Treat's information: @Html.DisplayFor(m => m.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.TreatId)

    @Html.LabelFor(m => m.Name)
    @Html.EditorFor(m => m.Name)
    @Html.LabelFor(m => m.Description)
    @Html.TextBoxFor(m => m.Description)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresTreats/Views/Treats/Index.cshtml
@{
    Layout = "_Layout";
}

@using PierresTreats.Models;

<h1>Treats List:</h1>

@if (Model.Count == 0)
{
    <h3>No treats have been added to your systme</h3>
    <p>@Html.ActionLink("Add new treats", "Create")</p>
}

<ul>
    @foreach (Treat treat in Model)
    {
        <li>Name: @Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId})

            Description: @Html.ActionLink($"{treat.Description}", "Details", new { id = treat.TreatId})

        </li>
    }
</ul>

<p>@Html.ActionLink("Add new treats", "Create")</p>